### PR TITLE
Fixed #22: do not send the first derivatives value

### LINKED ISSUE #22: First value is not consistent with following values
**Environment**:
- **Kernel** (e.g. `uname -a`): Linux 4.4.6

**What happened**:
plugin disk is not consistent in metrics type. First value is sent as-is (like a type COUNTER) while following values are the differences with the previous values (like a type GAUGE). It makes it really hard to create meaningful graph because at each  restart of snapd, the first value will be way higher than the others. Eg: 148146814861 -> 26 -> 24 -> 32

**What you expected to happen**:
The first value should not be sent. Wait an interval to calculate the derivative.

**Steps to reproduce it** (as minimally and precisely as possible):
1. just use the disk plugin.

### PR DESCRIPTION
**Pull request by IzabellaRaulin**
Fixes #22

Summary of changes:
- do not send the first derived values
- handle dynamic metrics in "CollectMetrics" in the model way
- added "calcGauge()" to set an value of `pending_ops` metric in separate place (before it was done in "calcDerivatives()" and do not skip this gauge-type metric in the first collection
- updated README.md:
  - added info about type of metric
  - added missing `pending_ops` metric to the metric list

How to verify it:
- run exemplary task manifest: in the first collection only gauge metric (_pending_ops_) is returned, the derived metrics are available from the second collection as expected

Testing done:
- legacy test
- run exemplary task manifest to verify that the first values of derive metrics are consistent

### CODE REVIEW

**Comment by candysmurf** [comment]
@IzabellaRaulin, the value of metric "/intel/procfs/disk/dm-0/octets_write" is pretty high comparing to other values. Do you mind double check to see if it's right?  This is my rough look after I upgrade my system to Mac Sierra. We can sync up more tomorrow.

File: disk/disk.go [hunk 1]
```diff
@@ -450,6 +464,11 @@ func parseMetricKey(k string) (disk, metric string) {
 	return result[0], result[1]
 }
 
+// createMetricKey returns metric key which includes disk name and name of metric, exemplary metric key is `sda/time_write`
+func createMetricKey(diskName string, metricName string) string {
```
Comment (IRCody) [inline disk/disk.go]: Is this safe given that `/` can now appear as part of the namespace?

File: disk/disk.go [hunk 2]
```diff
@@ -433,11 +441,17 @@ func createNamespace(name string) []string {
...
-	// skip prefix in namespace
-	metric := ns[len(prefix):]
-	return strings.Join(metric, "/")
+// parseNamespace returns extracted disk ID and metric key from a given namespace
+func parseNamespace(ns core.Namespace) (string, string, error) {
+	if len(ns.Strings()) <= len(prefix) {
+		return "", "", fmt.Errorf("Cannot parse a given namespace %s, it's too short (expected length > %d)", ns.Strings(), len(prefix))
+	}
+	// skip prefix in namespace to get metric key
+	metricKey := strings.Join(ns.Strings()[len(prefix):], "/")
```
Comment (candysmurf) [inline disk/disk.go]: it joins ns then it gets split in the parseMetricKey. Can we combine them into one so no joining and splitting is needed?

File: disk/disk.go (hunk 1 above)
Comment (IzabellaRaulin) [inline disk/disk.go]: Only if diskName would contain `/`, where by diskName is a device listed in /proc/diskstats. According metricName - this is defined in [disk.go#L53](https://github.com/intelsdi-x/snap-plugin-collector-disk/blob/master/disk/disk.go#L53) explicitly and cannot include slash. 

Just in case, I changed this to use `core.Separator` as a separator.

File: disk/disk.go (hunk 2 above)
Comment (IzabellaRaulin) [inline disk/disk.go]: Good caught, done. Please, verify if is ok now: [disk.go#L437](https://github.com/IzabellaRaulin/snap-plugin-collector-disk/blob/fix22_copy/disk/disk.go#L437)

File: disk/disk.go (hunk 1 above)
Comment (IRCody) [inline disk/disk.go]: It was a more general comment. I didn't notice that the strings were-predefined. Thanks for clarifying.

**Comment by candysmurf** [comment]
LGTM

File: disk/disk.go [hunk 3]
```diff
@@ -191,56 +190,58 @@ func (dc *DiskCollector) CollectMetrics(mts []plugin.MetricType) ([]plugin.Metri
 			return nil, err
 		}
 	}
+
```
Comment (candysmurf) [inline disk/disk.go]: @IzabellaRaulin, line 187 still skips the derivative calculation.  Would you please take another look, if it needs to be changed?

**Comment by candysmurf** [comment]
@IzabellaRaulin, I'm probably very confused:-). I thought we only send derivatives including the first set of values. No raw data at this time.  Raw data is for the future enhancement.

File: disk/disk.go (hunk 3 above)
Comment (IzabellaRaulin) [inline disk/disk.go]: Yes, that is ok -  calculation of derivatives based on data from presence and past (previous one), so for the first collection there is no previous data, so skipping this is ok. I put all this code with comments below to clarify how this collection works:

```
 	// get presence disk stats
 	if err := dc.getDiskStats(procFilePath); err != nil {
 		return nil, err
 	}
 
 	//  for first collecting skip derivatives calculation
 	if !first {
 		// calculate derivatives based on data (presence) and previous one; results stored in dc.output
 		if err := dc.calcDerivatives(); err != nil {
  			return nil, err
  		}
  	}
```

**Comment by IzabellaRaulin** [comment]
@candysmurf, I do not know whether I correctly understood what confusing you. Maybe I will explain that how it works:
  - **for every collection** disk statistics are gathered (which are raw) and stored them in `[dc.data](https://github.com/IzabellaRaulin/snap-plugin-collector-disk/blob/fix_22/disk/disk.go#L76); these data are needed to calculate derivatives
  - **for each collection except the first one** derivatives are calculated (based on raw data stored in [dc.data](https://github.com/IzabellaRaulin/snap-plugin-collector-disk/blob/fix_22/disk/disk.go#L76) and [dc.dataPrev](https://github.com/IzabellaRaulin/snap-plugin-collector-disk/blob/fix_22/disk/disk.go#L77) and the results from this calculation are kept in [dc.output](https://github.com/IzabellaRaulin/snap-plugin-collector-disk/blob/fix_22/disk/disk.go#L78)

There is only a one metric - `pending_ops` which is a gauge type, so this metric is returned as it is. The rest of currently available metrics are a derive type - see [README.md](https://github.com/IzabellaRaulin/snap-plugin-collector-disk/tree/fix_22#collected-metrics)

This plugin worked before in that way that is explained above, but after introduction of this line [master/disk/disk.go#L212](https://github.com/intelsdi-x/snap-plugin-collector-disk/blob/master/disk/disk.go#L212) the first derivatives values are sent as raw, what breaks consistency (https://github.com/intelsdi-x/snap-plugin-collector-disk/issues/22).  This pull request fixes that :)


According:
> No raw data at this time. Raw data is for the future enhancement.  

Yes, that's right.

**Comment by candysmurf** [comment]
Thanks @IzabellaRaulin for details. LGTM
